Old_world_caravans.awards = {
  wh_main_sc_emp_empire = {
    ["wh3_main_combi_region_kraka_drak"] = "owc_main_anc_rune_master_rune_of_grungni",
    ["wh3_main_combi_region_monument_of_the_moon"] = "owc_dlc12_anc_magic_standard_exalted_banner_of_xapati",
    ["wh3_main_combi_region_temple_of_kara"] = "owc_dlc12_anc_magic_standard_totem_pole_of_destiny",
    ["wh3_main_combi_region_lothern"] = "owc_main_anc_talisman_diamond_guardian_phoenix",
    ["wh3_main_combi_region_gaean_vale"] = "owc_main_anc_talisman_emerald_collar",
    ["wh3_main_combi_region_kings_glade"] = "owc_dlc16_anc_armour_twilight_helm_3",
    ["wh3_main_combi_region_myrmidens"] = "owc_main_anc_caravan_warrant_of_trade",
    ["wh3_main_combi_region_miragliano"] = "owc_main_anc_caravan_grant_of_land",
    ["wh3_main_combi_region_magritta"] = "owc_main_anc_caravan_spy_in_court",
    ["wh3_main_combi_region_kislev"] = "owc_main_anc_talisman_blood_of_the_motherland",
    ["wh3_main_combi_region_karak_kadrin"] = "owc_main_anc_rune_master_rune_of_battle",
    ["wh3_main_combi_region_karaz_a_karak"] = "owc_main_anc_rune_master_rune_of_valaya",
    ["wh3_main_combi_region_zhufbar"] = "owc_dlc10_dwf_anc_enchanted_item_ironwardens_tankard",
    ["wh3_main_combi_region_sudenburg"] = "owc_dlc09_anc_talisman_collar_of_shakkara",
    ["wh3_main_combi_region_khemri"] = "owc_dlc09_anc_enchanted_item_vambraces_of_the_sun",
  },
  wh_main_sc_dwf_dwarfs = {
    ["wh3_main_combi_region_marienburg"] = "dwf_caravan_marienburg",
    ["wh3_main_combi_region_altdorf"] = "dwf_caravan_reikland",
    ["wh3_main_combi_region_massif_orcal"] = "dwf_caravan_massif_orcal",
    ["wh3_main_combi_region_karak_dum"] = "dwf_caravan_karak_dum",
    ["wh3_main_combi_region_karak_ziflin"] = "dwf_caravan_karak_ziflin",
    ["wh3_main_combi_region_karak_azorn"] = "dwf_caravan_karak_azorn",
    ["wh3_main_combi_region_karak_zorn"] = "dwf_caravan_karak_zorn",
    ["wh3_main_combi_region_vulture_mountain"] = "dwf_caravan_vulture_mountain",
    ["wh3_main_combi_region_kraka_drak"] = "dwf_caravan_kraka_drak",
    ["wh3_main_combi_region_karak_krakaten"] = "dwf_caravan_karak_krakaten",
    ["wh3_main_combi_region_khemri"] = "dwf_caravan_khemri",
    ["wh3_main_combi_region_lahmia"] = "dwf_caravan_lahmia",
    ["wh3_main_combi_region_bordeleaux"] = "dwf_caravan_bordeleaux",
    ["wh3_main_combi_region_miragliano"] = "dwf_caravan_tilea",
    ["wh3_main_combi_region_erengrad"] = "dwf_caravan_erengrad",
    ["wh3_main_combi_region_kislev"] = "dwf_caravan_kislev",

  },
  wh3_main_sc_cth_cathay = {
    ["wh3_main_combi_region_couronne"] = "owc_dlc07_anc_magic_standard_errantry_banner",
    ["wh3_main_combi_region_castle_carcassonne"] = "owc_anc_follower_strange_bretonnian_peasant",
    ["wh3_main_combi_region_khemri"] = "owc_dlc09_anc_enchanted_item_vambraces_of_the_sun",
    ["wh3_main_combi_region_miragliano"] = "owc_main_anc_follower_empire_estalian_diestro",
    ["wh3_main_combi_region_kraka_drak"] = "owc_main_anc_rune_master_rune_of_valaya",
    ["wh3_main_combi_region_kings_glade"] = "owc_dlc16_anc_armour_dragon_cuirass_3",
    ["wh3_main_combi_region_lothern"] = "owc_main_anc_talisman_diamond_guardian_phoenix",

  },
  wh_main_sc_brt_bretonnia = {
    ["wh3_main_combi_region_temple_of_tlencan"] = "owc_dlc12_anc_magic_standard_exalted_banner_of_xapati",
    ["wh3_main_combi_region_temple_of_kara"] = "owc_dlc12_anc_magic_standard_totem_pole_of_destiny",
    ["wh3_main_combi_region_lothern"] = "owc_main_anc_talisman_diamond_guardian_phoenix",
    ["wh3_main_combi_region_gaean_vale"] = "owc_main_anc_talisman_emerald_collar",
    ["wh3_main_combi_region_kings_glade"] = "owc_dlc16_anc_weapon_dragon_spear_3",
    ["wh3_main_combi_region_waterfall_palace"] = "owc_dlc16_anc_talisman_twilight_horn_3",
    ["wh3_main_combi_region_myrmidens"] = "owc_main_anc_caravan_warrant_of_trade",
    ["wh3_main_combi_region_miragliano"] = "owc_main_anc_caravan_grant_of_land",
    ["wh3_main_combi_region_magritta"] = "owc_main_anc_follower_empire_estalian_diestro",
    ["wh3_main_combi_region_kislev"] = "owc_main_anc_talisman_blood_of_the_motherland",
    ["wh3_main_combi_region_karak_kadrin"] = "owc_dlc10_dwf_anc_weapon_gate_keepers_hammer",
    ["wh3_main_combi_region_karaz_a_karak"] = "owc_main_anc_rune_master_rune_of_sanctuary",
    ["wh3_main_combi_region_zhufbar"] = "owc_dlc10_dwf_anc_enchanted_item_ironwardens_tankard",
    ["wh3_main_combi_region_copher"] = "owc_dlc09_anc_talisman_collar_of_shakkara",
    ["wh3_main_combi_region_zandri"] = "owc_dlc09_anc_weapon_blade_of_mourning_fire",
  }
}