Old_world_caravans.start_units = {
  emp_caravan_skill_innate_empire = {
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_crossbowmen",
    "wh_main_emp_inf_crossbowmen",
    "wh2_dlc13_emp_inf_huntsmen_0",
    "wh2_dlc13_emp_inf_huntsmen_0",
    "wh_main_emp_inf_spearmen_1",
    "wh_main_emp_inf_spearmen_1",
  },
  emp_caravan_skill_innate_kislev = {
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_crossbowmen",
    "wh_main_emp_inf_crossbowmen",
    "wh3_main_pro_ksl_inf_armoured_kossars_0",
    "wh3_main_pro_ksl_inf_armoured_kossars_0",
    "wh3_main_pro_ksl_cav_winged_lancers_0",
    "wh3_main_pro_ksl_cav_winged_lancers_0",
  },
  emp_caravan_skill_innate_dwarfs = {
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_crossbowmen",
    "wh_main_emp_inf_crossbowmen",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_quarrellers_0",
    "wh_main_dwf_inf_quarrellers_0",
  },
  emp_caravan_skill_innate_bretonnia = {
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_crossbowmen",
    "wh_main_emp_inf_crossbowmen",
    "wh_dlc07_brt_cav_knights_errant_0",
    "wh_dlc07_brt_cav_knights_errant_0",
    "wh_dlc07_brt_inf_battle_pilgrims_0",
    "wh_dlc07_brt_inf_battle_pilgrims_0",
  },
  emp_caravan_skill_innate_ogres = {
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_crossbowmen",
    "wh_main_emp_inf_crossbowmen",
    "wh3_main_ogr_inf_maneaters_0",
    "wh3_main_ogr_inf_maneaters_1",
  },
  emp_caravan_skill_innate_elves = {
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_crossbowmen",
    "wh_main_emp_inf_crossbowmen",
    "wh2_main_hef_inf_spearmen_0",
    "wh2_main_hef_inf_spearmen_0",
    "wh2_main_hef_inf_archers_1",
    "wh2_main_hef_inf_archers_1",
  },
  emp_caravan_skill_innate_artillery = {
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_crossbowmen",
    "wh_main_emp_inf_crossbowmen",
    "wh_main_emp_art_great_cannon",
    "wh_main_emp_art_mortar",
    "wh_main_emp_inf_handgunners",
  },
  emp_caravan_skill_innate_cavalry = {
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_crossbowmen",
    "wh_main_emp_inf_crossbowmen",
    "wh_main_emp_cav_empire_knights",
    "wh_main_emp_cav_empire_knights",
    "wh_main_emp_cav_empire_knights",
    "wh_main_emp_cav_empire_knights",
  },
  emp_caravan_skill_innate_vagons = {
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_crossbowmen",
    "wh_main_emp_inf_crossbowmen",
    "wh2_dlc13_emp_veh_war_wagon_0",
    "wh2_dlc13_emp_veh_war_wagon_0",
  },
  emp_caravan_skill_innate_militia = {
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_crossbowmen",
    "wh_dlc04_emp_inf_free_company_militia_0",
    "wh_dlc04_emp_inf_free_company_militia_0",
    "wh_dlc04_emp_inf_free_company_militia_0",
    "wh_main_emp_cav_pistoliers_1",
  },
  emp_caravan_skill_innate_fanatic = {
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_crossbowmen",
    "wh_main_emp_inf_crossbowmen",
    "wh_dlc04_emp_inf_flagellants_0",
    "wh_dlc04_emp_inf_flagellants_0",
    "wh_dlc04_emp_inf_flagellants_0",
  },
  emp_caravan_skill_innate_heavy = {
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_crossbowmen",
    "wh_main_emp_inf_crossbowmen",
    "wh_main_emp_inf_greatswords",
    "wh_main_emp_inf_greatswords",
  },
  emp_caravan_skill_innate_pyro = {
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_swordsmen",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_handgunners",
    "wh_main_emp_inf_handgunners",
    "wh_main_emp_inf_handgunners",
    "wh_main_emp_cav_outriders_0",
    "wh_main_emp_cav_outriders_1",
  },
  dwf_caravan_skill_innate_empire = {
    "wh_main_dwf_inf_longbeards",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_quarrellers_0",
    "wh_main_dwf_inf_quarrellers_0",
    "wh_main_emp_inf_halberdiers",
    "wh_main_emp_inf_halberdiers",
    "wh_dlc04_emp_inf_free_company_militia_0",
    "wh_dlc04_emp_inf_free_company_militia_0",
  },
  dwf_caravan_skill_innate_kislev = {
    "wh_main_dwf_inf_longbeards",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_quarrellers_0",
    "wh_main_dwf_inf_quarrellers_0",
    "wh3_main_pro_ksl_inf_armoured_kossars_0",
    "wh3_main_pro_ksl_inf_armoured_kossars_0",
    "wh3_main_pro_ksl_cav_winged_lancers_0",
    "wh3_main_pro_ksl_cav_winged_lancers_0",
  },
  dwf_caravan_skill_innate_miners = {
    "wh_main_dwf_inf_longbeards",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_quarrellers_0",
    "wh_main_dwf_inf_quarrellers_0",
    "wh_main_dwf_inf_miners_1",
    "wh_main_dwf_inf_miners_1",
    "wh_main_dwf_inf_miners_1",
  },
  dwf_caravan_skill_innate_slayers = {
    "wh_main_dwf_inf_longbeards",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_quarrellers_0",
    "wh_main_dwf_inf_quarrellers_0",
    "wh_main_dwf_inf_slayers",
    "wh_main_dwf_inf_slayers",
    "wh_main_dwf_inf_slayers",
  },
  dwf_caravan_skill_innate_longbeards = {
    "wh_main_dwf_inf_longbeards",
    "wh_main_dwf_inf_longbeards",
    "wh_main_dwf_inf_longbeards",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_quarrellers_0",
    "wh_main_dwf_inf_quarrellers_0",
  },
  dwf_caravan_skill_innate_rangers = {
    "wh_main_dwf_inf_longbeards",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_dlc06_dwf_inf_rangers_0",
    "wh_dlc06_dwf_inf_rangers_0",
    "wh_dlc06_dwf_inf_bugmans_rangers_0",
    "wh_dlc06_dwf_inf_bugmans_rangers_0",
  },
  dwf_caravan_skill_innate_thunderers = {
    "wh_main_dwf_inf_longbeards",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_thunderers_0",
    "wh_main_dwf_inf_thunderers_0",
    "wh_main_dwf_inf_thunderers_0",
    "wh_main_dwf_inf_thunderers_0",
  },
  dwf_caravan_skill_innate_grudge_thrower = {
    "wh_main_dwf_inf_longbeards",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_quarrellers_0",
    "wh_main_dwf_inf_quarrellers_0",
    "wh_main_dwf_art_grudge_thrower",
    "wh_main_dwf_art_grudge_thrower",
  },
  dwf_caravan_skill_innate_organ_gun = {
    "wh_main_dwf_inf_longbeards",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_quarrellers_0",
    "wh_main_dwf_inf_quarrellers_0",
    "wh_main_dwf_art_organ_gun",
  },
  dwf_caravan_skill_innate_hammerers = {
    "wh_main_dwf_inf_hammerers",
    "wh_main_dwf_inf_hammerers",
    "wh_main_dwf_inf_hammerers",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_dwarf_warrior_0",
    "wh_main_dwf_inf_quarrellers_0",
    "wh_main_dwf_inf_quarrellers_0",
  },
}
