Old_world_caravans.threat_weight_by_culture = {
  wh_dlc03_sc_bst_beastmen = 3,
  wh_main_sc_grn_greenskins = 3,
  wh_main_sc_vmp_vampire_counts = 2,
  wh_dlc05_sc_wef_wood_elves = 1,
  wh_dlc08_sc_nor_norsca = 3,
  wh2_dlc11_sc_cst_vampire_coast = 2,
  wh2_main_sc_def_dark_elves = 3,
  wh2_main_sc_lzd_lizardmen = 1,
  wh3_main_sc_ogr_ogre_kingdoms = 1,
  wh_main_sc_teb_teb = 1,
  wh2_main_sc_skv_skaven = 2,
  wh2_dlc09_sc_tmb_tomb_kings = 1,
  wh3_main_sc_kho_khorne = 3,
  wh3_main_sc_sla_slaanesh = 3,
  wh3_main_sc_tze_tzeentch = 3,
  wh3_main_sc_nur_nurgle = 3,
}
