Old_world_caravans.minor_without_caravans = {
  wh2_dlc15_dwf_clan_helhein = true,
  wh2_main_dwf_greybeards_prospectors = true,
  wh2_main_dwf_karak_zorn = true,
  wh2_main_dwf_spine_of_sotek_dwarfs = true,
  wh_main_dwf_karak_norn = true,
  wh3_main_dwf_karak_azorn = true,
  wh2_main_brt_thegans_crusaders = true,
  wh2_main_brt_knights_of_the_flame = true,
  wh2_main_brt_knights_of_origo = true,
  cr_brt_leofrics_fellowship = true,
  cr_emp_cult_of_ulric = true,
  cr_ksl_heldegrad = true,
  cr_ksl_order_of_the_winter_sun = true,
  wh_main_dwf_karak_ziflin = true,
  cr_dwf_clan_durazgrund = true,
  cr_emp_carroburg = true,
  wh3_dlc20_brt_march_of_couronne = true,

}